# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
    #Hành động
jobs:
#CI
  test:
    runs-on: ubuntu-latest
    # máy chủ mới
    strategy:
      matrix:
      #tạo môi trường
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        # Phiên bản Node.js
    steps:
    #git clone
    - uses: actions/checkout@v3
    #Cài node
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    #thực hiện câu lệnh cài nodemodun
    - run: npm install
    #chạy test
    - run: npm test
  #CD
  deloy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Remove folder .git
        run: rm -rf .git
      - name: Show project
        run: ls -la
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      # tạo thư mục mới- chép key trong thư mục qua id_rsa - cấp quyền
      - name: deloy code to server
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r ../demo-ci-cd ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:~/html
